### ISSUE TITLE
客户端输入/all !!bingo或!!bingo均无反应，服务端输入!!bingo能正常显示

### ISSUE THREAD

**Issue by snpdzk** [FAS-Server/FAS-bingo#6]
服务端日志：
C:\server\bingo>mcdreforged
MCDReforged 2.11.0 is starting up
MCDReforged is open source, u can find it here: https://github.com/Fallen-Breath/MCDReforged
[MCDR] [14:55:50] [MainThread/INFO]: 语言已设置为 zh_cn
[MCDR] [14:55:50] [MainThread/INFO]: 编码 / 解码方式已设置为 utf8 / utf8
[MCDR] [14:55:50] [MainThread/INFO]: 插件文件夹列表:
[MCDR] [14:55:50] [MainThread/INFO]: - plugins
[MCDR] [14:55:50] [MainThread/ERROR]: Fail to load info handler from "handler.bingo_handler.BingoHandler"
Traceback (most recent call last):
  File "C:\Users\snp\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\handler\server_handler_manager.py", line 48, in register_handlers
    handler_class = class_util.load_class(class_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snp\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\utils\class_util.py", line 17, in load_class
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\snp\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'handler'
[MCDR] [14:55:50] [MainThread/ERROR]: Fail to load handler with name "bingo_handler"
[MCDR] [14:55:50] [MainThread/ERROR]: Fallback basic handler is used, MCDR might not works correctly
[MCDR] [14:55:50] [MainThread/INFO]: 解析处理器已设置为 bingo_handler
[MCDR] [14:55:50] [MainThread/INFO]: MCDReforged正于Python 3.11.3环境中运行
[MCDR] [14:55:50] [TaskExecutor/INFO]: 刷新所有插件中
[MCDR] [14:55:50] [TaskExecutor/INFO]: 插件 bingo_menu@1.1.1 已加载
[MCDR] [14:55:50] [TaskExecutor/INFO]: 共加载: 1 个插件; 已加载插件数: 3
[MCDR] [14:55:50] [MainThread/INFO]: 正在启动服务端，启动参数为 "run.bat"
[MCDR] [14:55:50] [MainThread/INFO]: 服务端正在以 PID 105596 运行中
[Server]
[Server] C:\server\bingo\server>java -Xms2G -Xmx4G -Dfile.encoding=UTF-8 -jar paper-1.20.1-196.jar nogui
[Server] Starting org.bukkit.craftbukkit.Main
[Server] *** Warning, you've not updated in a while! ***
[Server] *** Please download a new build as per instructions from https://papermc.io/downloads/paper ***
[Server] System Info: Java 17 (Java HotSpot(TM) 64-Bit Server VM 17+35-LTS-2724) Host: Windows 10 10.0 (amd64)
[Server] Loading libraries, please wait...
[Server] 2023-10-21 14:55:52,066 ServerMain WARN Advanced terminal features are not available in this environment
[Server] [14:55:52 WARN]: [oshi.driver.windows.perfmon.PerfmonDisabled] Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[Server] [14:55:57 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[Server] [14:55:58 INFO]: Loaded 7 recipes
[Server] [14:55:59 INFO]: Starting minecraft server version 1.20.1
[Server] [14:55:59 INFO]: Loading properties
[Server] [14:55:59 INFO]: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
[Server] [14:56:00 INFO]: Server Ping Player Sample Count: 12
[Server] [14:56:00 INFO]: Using 4 threads for Netty based IO
[Server] [14:56:00 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
[Server]     We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
[Server]     For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[Server] [14:56:00 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 6 worker threads, and gen parallelism of 6 threads
[Server] [14:56:00 INFO]: Default game type: SURVIVAL
[Server] [14:56:00 INFO]: Generating keypair
[Server] [14:56:00 INFO]: Starting Minecraft server on *:25666
[Server] [14:56:00 INFO]: Using default channel type
[Server] [14:56:00 INFO]: Paper: Using Java compression from Velocity.
[Server] [14:56:00 INFO]: Paper: Using Java cipher from Velocity.
[Server] [14:56:00 INFO]: [MinecraftBingo] Loading server plugin MinecraftBingo v1.10.0
[Server] [14:56:00 INFO]: Server permissions file permissions.yml is empty, ignoring it
[Server] [14:56:00 INFO]: [MinecraftBingo] Enabling MinecraftBingo v1.10.0
[Server] [14:56:00 INFO]: [MinecraftBingo] Creating Game instance
[Server] [14:56:00 INFO]: Preparing level "world"
[Server] [14:56:01 INFO]: Preparing start region for dimension minecraft:overworld
[Server] [14:56:01 INFO]: Time elapsed: 346 ms
[Server] [14:56:01 INFO]: [MinecraftBingo] Setting overworld world border...
[Server] [14:56:01 INFO]: [MinecraftBingo] Locating structure minecraft:stronghold to determine border center
[Server] [14:56:02 INFO]: [MinecraftBingo] Overworld border set
[Server] [14:56:02 INFO]: Preparing start region for dimension minecraft:the_nether
[Server] [14:56:03 INFO]: Time elapsed: 528 ms
[Server] [14:56:03 INFO]: [MinecraftBingo] Setting nether world border...
[Server] [14:56:03 INFO]: [MinecraftBingo] Locating structure minecraft:fortress to determine border center
[Server] [14:56:03 INFO]: [MinecraftBingo] Nether border set
[Server] [14:56:03 INFO]: Preparing start region for dimension minecraft:the_end
[Server] [14:56:03 INFO]: Time elapsed: 16 ms
[Server] [14:56:03 INFO]: Running delayed init tasks
[Server] [14:56:03 INFO]: Done (3.884s)! For help, type "help"
[Server] [14:56:03 INFO]: Timings Reset
[Server] [14:56:12 INFO]: UUID of player snp_dzk is e948d6a8-339d-46a3-a3f4-2476abea101d
[Server] [14:56:13 INFO]: + snp_dzk joined
[Server] [14:56:13 INFO]: snp_dzk[/192.168.31.115:53275] logged in with entity id 171 at ([world]2494.0, 67.0, -249.0)
[Server] [14:56:22 INFO]: snp_dzk issued server command: /all !!bingo
[Server] [14:56:22 INFO]: snp_dzk: !!bingo
> !!bingo
[MCDR] [14:56:32] [TaskExecutor/INFO]: -----FAS bingo menu V1.1.1-----
[MCDR] [14:56:32] [TaskExecutor/INFO]: Bingo 小游戏管理插件
[MCDR] [14:56:32] [TaskExecutor/INFO]: !!bg 显示快捷控制面板
[MCDR] [14:56:32] [TaskExecutor/INFO]: !!bingo 显示这条帮助信息
[MCDR] [14:56:32] [TaskExecutor/INFO]: !!bingo team 选择队伍
[MCDR] [14:56:32] [TaskExecutor/INFO]: !!bingo vote 进行投票
[MCDR] [14:56:32] [TaskExecutor/INFO]: !!bingo config 快捷修改游戏设置
[MCDR] [14:56:32] [TaskExecutor/INFO]: !!bingo mode 修改游戏模式
[MCDR] [14:56:32] [TaskExecutor/INFO]: !!bingo timer 开/关限时模式
[MCDR] [14:56:32] [TaskExecutor/INFO]: !!bingo timer [<限时时长>] 修改限时模式时间，单位：分钟
[MCDR] [14:56:32] [TaskExecutor/INFO]: !!bingo card 修改物品稀有度

**Comment by 401U** [comment]
需要为mcdr配置handler，因为bingo游戏的聊天记录格式比较特殊

**Comment by snpdzk** [comment]
![image](https://github.com/FAS-Server/bingo-menu/assets/130619899/df424e82-0dcc-4fc1-9959-ba15d130c6f9)
![image](https://github.com/FAS-Server/bingo-menu/assets/130619899/b1b9e7c8-0fd9-4d40-9245-0546aaac1b24)
![image](https://github.com/FAS-Server/bingo-menu/assets/130619899/3c4903cf-00c1-4a87-ae6e-0adeeab24616)
![image](https://github.com/FAS-Server/bingo-menu/assets/130619899/620b6593-fcb2-4763-a557-db397df831e7)
![image](https://github.com/FAS-Server/bingo-menu/assets/130619899/28166023-f550-4e3f-bb4d-6f869b75cb32)
![image](https://github.com/FAS-Server/bingo-menu/assets/130619899/68f962c9-e578-4d11-a231-939e13645bf9)

**Comment by 401U** [comment]
关于handler的使用，可参考mcdr的文档 https://mcdreforged.readthedocs.io/zh-cn/latest/customize/handler.html
